### ISSUE TITLE
Don't commit on develop / use feature model / revert commits

### ISSUE THREAD

**Issue by sacdallago** [Rostlab/JS16_ProjectC_Group10#1]
@mbandle you commited on the develop branch (1523017d5d47b0896ced64238e85cdaef865a756), this is not what you should do.

Please:
- [x] Revert your commit and bring develop back to the initial state ( ef08fcc48309331d0ef410b9bc53f7bbfd618ee9 )
- [x] Open a branch for the feature you work on, branching off from develop
- [x] If you are already done with your feature, open a pull request

We would like you to implement the feature model. If you don't know how this works, please have a look at https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow/ and the video in which I explain it https://youtu.be/twKtSfLcKxI?t=12m25s
# I need to see pull request to know: who did what

:dancer: hope this makes you understand why I do this :D

**Comment by tPiffrader** [comment]
@sacdallago So, if I got it right... Only who makes the pull request, even if all members of the team worked on it, gets the recognition of the code?
If this is right... This would change our workflow a bit... Because, we as a team thought also of working together on one laptop...

**Comment by sacdallago** [comment]
@tPiffrader oh, that's not suuuuuch a good idea! You don't have that much time, you will want to work also at home, also from your laptop (just saying). And yes: we look at who committed the code to guess who worked on what and we use [metrics](https://rostlab.org/~gyachdav/js16/html/). You may understand that we can't police 35 ppl, so this is our way of doing it. Rotate computers if you really do everything together.

**Comment by tPiffrader** [comment]
@sacdallago OK

**Comment by sacdallago** [comment]
@AlexMoroz please use the feature model also for your part / the tests.
@tPiffrader and @mbandle are already experts in this regards, they can help you with any doubt.

There's no need to revert commits now, it's too late: just remember it for the future! And close this issue, so I know that you got the message ;)
