### ISSUE TITLE
Rename + implement function of Search-bar

### ISSUE THREAD

**Issue by tPiffrader** [Rostlab/JS16_ProjectC_Group10#10]
- [x] rename it to filter
- [x] implement the filtering of characters
- [x] connect the filter to the character list

**Comment by bandle** [comment]
I will move all the person data to a separate js which can be later replaced by the database. 
So we can use it for generating the sidebar and the search

**Comment by bandle** [comment]
The Basics are working now we have to specify new goals how the filter and the persons should react
