### ISSUE TITLE
Polygons for Houses

### ISSUE THREAD

**Issue by bandle** [Rostlab/JS16_ProjectC_Group10#112]
- [x] Build a polygon editor
- [x] Gather house data
- [x] Bring it to the mockup
- [x] Make a button to google display
- [x] Assign Colors to the realms

**Comment by AlexBeischl** [comment]
I will create the Polygons for the realms of Essos within the next 2 days

**Comment by AlexBeischl** [comment]
I'm sorry @sacdallago but I don't have a screenshot for you today

![gntm](https://cloud.githubusercontent.com/assets/17533952/13821860/a7df03ea-eba3-11e5-8e41-547f14bc6c02.jpg)
(we need some surprises for you tomorrow)

**Comment by sacdallago** [comment]
I was happily surprised today :dancer:

**Comment by AlexBeischl** [comment]
Added some more polygons, see New Editor, next uploads will be in this branch again...

**Comment by tPiffrader** [comment]
pull request is on... 
small insight how it looked like clicking realms :sweat_smile: 
![screen shot 2016-03-24 at 00 37 04](https://cloud.githubusercontent.com/assets/17313200/14004248/e2484982-f158-11e5-8087-073c67fc07c5.png)
branch is https://github.com/Rostlab/JS16_ProjectC_Group10/pull/198

**Comment by sacdallago** [comment]
:D you are gonna have the strongest right index finger in history.

**Comment by gyachdav** [comment]
:D

**Comment by tPiffrader** [comment]
:smiley: :smiley:
