### ISSUE TITLE
Prettify name on npm

### ISSUE THREAD

**Issue by sacdallago** [Rostlab/JS16_ProjectC_Group10#116]
Hi @/all 
Please publish your package on npm with some catchy-pretty name. At the end of the day you want to have many people download the package, so:
https://www.npmjs.com/package/rostlab-js16-c10 is not catchy nor pretty :D

**Comment by AlexMoroz** [comment]
Is "got-map" is catchy and pretty enough?

**Comment by tPiffrader** [comment]
Nooooo :-1: :smiley:

**Comment by AlexMoroz** [comment]
No problem.

**Comment by tPiffrader** [comment]
hahahaha

**Comment by sacdallago** [comment]
AHAHAHAHAHAHAH

> No problem.

+

> @AlexMoroz assigned @tPiffrader 

is by far the best thing I have seen in these last weeks on GitHub. No but seriously got-map may actually do. It's a word game and a pretty good one too. But leave out the slash, if you can.

**Comment by AlexMoroz** [comment]
I renamed it to "gotmap" and published it.

**Comment by sacdallago** [comment]
@AlexMoroz is it also possible to delete the old package form NPM? https://www.npmjs.com/package/rostlab-js16-c10 is still there.

Also, https://github.com/Rostlab/JS16_ProjectF/issues/17 is trying to integrate but is unsuccessful :D

**Comment by sacdallago** [comment]
P.S.: as a rule of thumb, you should be able to require the package and use https://tonicdev.com/npm/gotmap to do something with it. This might mean putting some example code on how to import and render the map using, for example, express and angular.. Or whatever you deem necessary!

**Comment by AlexMoroz** [comment]
Delete the old package - done.

Integrate to project F - it's too early, package isn't finished yet.

**Comment by sacdallago** [comment]
(Y) but start worrying about that :D

**Comment by AlexMoroz** [comment]
> P.S.: as a rule of thumb, you should be able to require the package

Actually we didn't come up with the decision about what to require [here](https://github.com/Rostlab/JS16_ProjectF/issues/5)

**Comment by AlexBeischl** [comment]
Is this Issue done?

**Comment by AlexMoroz** [comment]
Yes, we are using "gotmap"

**Comment by sacdallago** [comment]
Sorry, forgot to close. @AlexMoroz tell your project mates `got*` is gonna be the official title of all npm published packages :)

**Comment by sacdallago** [comment]
-- thanks <3

**Comment by AlexBeischl** [comment]
@AlexMoroz you are a trendsetter :wink:
