### ISSUE TITLE
Use tiles remotely

### ISSUE THREAD

**Issue by AlexMoroz** [Rostlab/JS16_ProjectC_Group10#117]

**Comment by bandle** [comment]
Done. We use the github tiles remotely

**Comment by sacdallago** [comment]
Where? I don't see a pull request nor a reference to this issue from any commit.
Also: this means you will use the tiles from your github repo online instead of from the local version of your repo?

**Comment by bandle** [comment]
We use the remote tiles since the beginning :)

**Comment by sacdallago** [comment]
Yeah, but I'm not getting the issue or the resolution of it at all :D

**Comment by AlexMoroz** [comment]
I thought that map is used from the local folder, but it actually is used remotely from github. The issue was incorrect.

**Comment by sacdallago** [comment]
OK, now it's clear

**Comment by sacdallago** [comment]
Whops! didn't mean to do that :D I'm tired you guys :zzz:
