### ISSUE TITLE
Display Dead People

### ISSUE THREAD

**Issue by bandle** [Rostlab/JS16_ProjectC_Group10#126]
Mark the spot where the person died on the map

**Comment by AlexBeischl** [comment]
- [x]  find a icon for the location of dead people
- [x]  map the data including deaths
- [x]  bring it into the mockup

**Comment by bandle** [comment]
Done

![bildschirmfoto 2016-03-16 um 15 19 03](https://cloud.githubusercontent.com/assets/11232638/13815328/75ae7b44-eb8a-11e5-96ba-741a509e3929.png)
![bildschirmfoto 2016-03-16 um 15 19 09](https://cloud.githubusercontent.com/assets/11232638/13815329/75af201c-eb8a-11e5-95d9-eb1b6a7cd833.png)

**Comment by sacdallago** [comment]
So we are back to screenshots I guess?  [I just... in the cake](https://www.youtube.com/watch?v=z7ZeQkjLQ2M)

**Comment by tPiffrader** [comment]
Live demo is coming up tomo :+1:
