### ISSUE TITLE
Images not accessible

### ISSUE THREAD

**Issue by yashha** [Rostlab/JS16_ProjectC_Group10#129]
`https://raw.githubusercontent.com/Rostlab/JS16_ProjectC_Group10/develop/tiles/bg/0/y0x2.png 404 (Not Found) y0x1.png:1 GET`
Update your links if you changed your path please

**Comment by bandle** [comment]
These images actually don't exist. Its a bug in leaflet that it tries to load them.
They are out of map bounds.

**Comment by yashha** [comment]
Can't you try to avoid loading them, I don't like errors in the browser. :grimacing:

**Comment by bandle** [comment]
We did already several attempts in the early stages: 
http://leafletjs.com/reference-1.0.0.html#tilelayer-bounds
But for some reason it doesn't work
But we can throw in some blank tiles if you like to avoid errors. ;)

Or do you have any other idea?

**Comment by yashha** [comment]
Some blank tiles would work for me :)

**Comment by yashha** [comment]
What about using this?
https://www.mapbox.com/

Or is that too much for nothing?

**Comment by bandle** [comment]
What do you exactly mean?

Basically mapbox.js is a leaflet plugin http://stackoverflow.com/questions/12262163/what-are-leaflet-and-mapbox-and-what-are-their-differences/23663848#23663848

**Comment by sacdallago** [comment]
@yashha leaflet is just a framework between mapbox, google maps, bing maps, OSM, OCM or in the case of our great **C10**, their own tiles and coordinate system.
Also: it's the state of the art on the web, it's too late to change it now, and it's fine to have some error in the console relative to tiles.

**Comment by yashha** [comment]
I thought about hosting the map there, the api looked easy to integrate, but I don't like their, pricing model, so forget about that :)
I don't think we get to 50k views, but to make sure we should host the map by ourselves.

**Comment by sacdallago** [comment]
:D oh trust me... We will get 50k+ views. And I'm not just saying out of fancyness, I know stuff.

I'll close this now.
