### ISSUE TITLE
Add all map labels

### ISSUE THREAD

**Issue by tPiffrader** [Rostlab/JS16_ProjectC_Group10#13]
- [x] Add most important cities (Kings landing, ...)
- [x] Add sea and bay names
- [x] Add region names
- [x] Add the smaller cities

**Comment by bandle** [comment]
I added the most important cities from the HBO page

**Comment by bandle** [comment]
I just stitched all the tiles together in one big map. 
After you labeled the important stuff, we can sp
Later on you can  split in tiles again and we have a new layer with labels.

**Comment by bandle** [comment]
@AlexBeischl did the photoshop work for regions, sea names and the sea. Now we have customized tiles with labels :+1: 

I imported and adjusted a dataset of 250+ cities (around 20 more to come in essos)
![bildschirmfoto 2016-03-06 um 02 15 22](https://cloud.githubusercontent.com/assets/11232638/13551646/7322fd6a-e341-11e5-9721-936218e45473.png)
![bildschirmfoto 2016-03-06 um 02 16 17](https://cloud.githubusercontent.com/assets/11232638/13551647/734e1482-e341-11e5-8169-3b6ef932087d.png)

**Comment by sacdallago** [comment]
:heart: :heart_eyes:

**Comment by bandle** [comment]
Now with icons it looks even better, we just have to set priorities to not show all labels
![bildschirmfoto 2016-03-06 um 20 34 41](https://cloud.githubusercontent.com/assets/11232638/13556486/06fd96aa-e3db-11e5-9c54-2bce16c6ca1f.png)
