### ISSUE TITLE
Pins should have different colors

### ISSUE THREAD

**Issue by tPiffrader** [Rostlab/JS16_ProjectC_Group10#14]
- [x] Pin-color should match the characters that are filtered
- [x] Only pins from the filtered character(s) should appear

**Comment by bandle** [comment]
First attempt on colorful pins:
![bildschirmfoto 2016-03-07 um 16 23 45](https://cloud.githubusercontent.com/assets/11232638/13573659/10a919f8-e481-11e5-9b0e-8a2a169ed7ec.png)
