### ISSUE TITLE
Documentation, documentation, documentation!

### ISSUE THREAD

**Issue by sacdallago** [Rostlab/JS16_ProjectC_Group10#141]
:D Documentation?

**Comment by tPiffrader** [comment]
You mean in the code or in the README?

**Comment by sacdallago** [comment]
Mainly README!

For example: how do you set the thing up? Where do I store the dependencies? Do I need to download them manually?

**Comment by tPiffrader** [comment]
Ok! We will take care^^

**Comment by bandle** [comment]
I´m doing a complete code refactor for the projects JS. 
Tobi is doing the readme. Should be finished today

**Comment by bandle** [comment]
I put all the things to the wiki and provided some links in the README

**Comment by sacdallago** [comment]
Have seen that! Thx

**Comment by sacdallago** [comment]
P.S.: I've noticed the configuration options are not specified?

**Comment by bandle** [comment]
Not yet I know - but we are working on it

**Comment by bandle** [comment]
Added the sample options to a new wiki page. Tomorrow we are beginning to explain it

**Comment by bandle** [comment]
@sacdallago @yashha First Draft for options is ready
https://github.com/Rostlab/JS16_ProjectC_Group10/wiki/Init-New-GoT-Map-and-Options

Now working on API docs

**Comment by sacdallago** [comment]
cool!

**Comment by bandle** [comment]
Everything done with some examples:
https://github.com/Rostlab/JS16_ProjectC_Group10/wiki

More Details are coming with time :)
