### ISSUE TITLE
City data source

### ISSUE THREAD

**Issue by kordianbruck** [Rostlab/JS16_ProjectC_Group10#143]
Hey,

please enlighten us where from exactly you fetched the cities in this file https://github.com/Rostlab/JS16_ProjectC_Group10/blob/develop/data/cities.js

We are currently discussing automating the import: https://github.com/Rostlab/JS16_ProjectA/issues/82

**Comment by bandle** [comment]
We generated the data ourself by using this editor
https://github.com/Rostlab/JS16_ProjectC_Group10/blob/develop/editor/editor.html
and this map
http://www.sermountaingoat.co.uk/map/

**Comment by kordianbruck** [comment]
Thanks!
