### ISSUE TITLE
Set generic data sources 

### ISSUE THREAD

**Issue by sacdallago** [Rostlab/JS16_ProjectC_Group10#145]
Hey team, nice presentation.

I wanted to open this a while ago but now seems like a good time, as you are on the polishing stage. This will also help @AlexMoroz .

Please make your code reusable, which means: define data sources in configuration files or similar for _everything_ you depend on. Specifically I'm referring to things like:
- https://github.com/Rostlab/JS16_ProjectC_Group10/blob/develop/mockup/js/map.js#L52

In the example above, you can set a default, but you should give the possibility to take the tiles from somewhere else (like a local server for quicker processing).

Put some thoughts into where stuff like this occurs in the code :)

I like what you did here:
- https://github.com/Rostlab/JS16_ProjectC_Group10/blob/develop/mockup/js/config.js#L1

**Comment by bandle** [comment]
I'm on it in the refactor branch.

**Comment by bandle** [comment]
Done #155
