### ISSUE TITLE
Center the map when character is selected

### ISSUE THREAD

**Issue by sacdallago** [Rostlab/JS16_ProjectC_Group10#146]
Shouldn't be too many lines of code! ;)

**Comment by sacdallago** [comment]
P.S.: you can use an average between lowest an highest X/Y points and center the map on the map on that average

**Comment by AlexBeischl** [comment]
Nice idea, didn't think about that :thought_balloon:

**Comment by sacdallago** [comment]
HA, I can still outthink someone in this group? Nice.

**Comment by bandle** [comment]
Wasn't as easy as it sounded but works #165

**Comment by bandle** [comment]
@sacdallago you can pull the updated version to your server and test it ;)

**Comment by sacdallago** [comment]
Before I do that: the last time, I had to (from the root of the repo `cp -r mockup/* .` because the root of the webserver is set to the root of the repo, but the "index" is in mockups. If I try to set the root to mockups it won't be able to read the dependencies as you go one folder back (like [here](https://github.com/Rostlab/JS16_ProjectC_Group10/blob/develop/mockup/mockup.html#L33) and [here](https://github.com/Rostlab/JS16_ProjectC_Group10/blob/develop/mockup/mockup.html#L9). I don't know _how_ it can work :D but it does...
Do you think there's a way to solve this problem without resorting to the `cp` trick?

**Comment by bandle** [comment]
@sacdallago I put in a demo.html in the root folder - just rename it to index

**Comment by bandle** [comment]
http://rostlab.github.io/JS16_ProjectC_Group10/

Just found another good solution

**Comment by sacdallago** [comment]
yeah :D github pages are aawwweeesssooommeeee
