### ISSUE TITLE
Who can I display

### ISSUE THREAD

**Issue by sacdallago** [Rostlab/JS16_ProjectC_Group10#147]
On the search, try to display which characters have Pahts defined (maybe a little :heavy_check_mark: or a change in color)

**Comment by AlexBeischl** [comment]
Ok, we will add it :smile:

**Comment by bandle** [comment]
Done while refactoring the code. 
At the moment I use a green border to show it but nice styling comes later.

**Comment by bandle** [comment]
Done #155

**Comment by gyachdav** [comment]
or rather do not display the ones with no paths. right now picking a character with no path and not seeing it on the map is confusing.

**Comment by AlexBeischl** [comment]
Hi @gyachdav ,

I would display the characters without path as well, Project F is currently thinking about a how to use popup, maybe we can add it there to prevent confusion.

**Comment by bandle** [comment]
We are also waiting for Project A to implement the character full-text search. https://github.com/Rostlab/JS16_ProjectA/issues/85
When this is ready we can show some pins for nearly every character.

**Comment by gyachdav** [comment]
Really??? You made me do a small happy dance now at Columbia circle. People are handing me their money. :p
