### ISSUE TITLE
Character Pins should be on the map

### ISSUE THREAD

**Issue by tPiffrader** [Rostlab/JS16_ProjectC_Group10#15]
- [x] Find or Generate data
- [x] Write Map Path Editor
- [x] Collect Episode Information
- [x] Assign Episode Data to the Path (Make the Editor Even better)
- [x] Bring it to the mockup
- [x] Style it nice

**Comment by bandle** [comment]
We found no data so we have to generate our own data. I started building a path editor.

Nedds Path is done :)  

![bildschirmfoto 2016-03-06 um 23 46 34](https://cloud.githubusercontent.com/assets/11232638/13557670/ce66e29a-e3f5-11e5-9508-2abd92d1ffaa.png)

**Comment by bandle** [comment]
It works :)

A Picture for you @sacdallago 
![bildschirmfoto 2016-03-07 um 22 38 01](https://cloud.githubusercontent.com/assets/11232638/13584146/5c2c1086-e4b5-11e5-8f17-20fd68cd627c.png)

Now we just have to generate the data and style it a bit nicer

**Comment by sacdallago** [comment]
You know I'm about to print and frame your screenshots and start populating the empty and sad walls of my student room, next to [Cyanide and Happiness](http://explosm.net/comics/4231/)
