### ISSUE TITLE
Data Editors

### ISSUE THREAD

**Issue by AlexBeischl** [Rostlab/JS16_ProjectC_Group10#151]
Refactor/ Change the editors to publish them for the fan-project as @gyachdav mentioned today
- [x]  Realms-Editor
- [x]  enable the Realms-Editor to load already stored Polygons again, to edit them 
- [x] fix the Polygon-Icon
- [x]  Path-Editor

**Comment by AlexBeischl** [comment]
The new Editor works like this:
By clicking on the Polygon-Icon on the left side, we create a new Polygon.
<img width="822" alt="bildschirmfoto 2016-03-18 um 00 27 29" src="https://cloud.githubusercontent.com/assets/17533952/13864292/7edd1cf4-eca0-11e5-83e0-0053e1a75898.png">

Then we just have to click at the points we want as corners/vertices of our Polygon. (By doing this we create a Polyline)
<img width="458" alt="bildschirmfoto 2016-03-18 um 00 27 12" src="https://cloud.githubusercontent.com/assets/17533952/13864294/85f9c0b4-eca0-11e5-9129-1436038753f8.png">
To finish a Polygone, we have to connect the Polylines endpoint to its startpoint.
<img width="527" alt="bildschirmfoto 2016-03-18 um 00 27 24" src="https://cloud.githubusercontent.com/assets/17533952/13864301/8f44162e-eca0-11e5-9adf-2aed0520d38d.png">
When we create a new Polygon, the old ones are still shown, which is very helpful considering neighboring borders.
<img width="680" alt="bildschirmfoto 2016-03-18 um 00 21 34" src="https://cloud.githubusercontent.com/assets/17533952/13864327/cb7ae4ec-eca0-11e5-9773-0e81af63011e.png">

To export the Polygons Coordinates, we can click on the button on the right top and copy the LatLng-Array into the realms.js in the data-folder.
<img width="605" alt="bildschirmfoto 2016-03-18 um 00 28 18" src="https://cloud.githubusercontent.com/assets/17533952/13864341/f044efde-eca0-11e5-8a5f-ebcb9a5b7ab1.png">

**Comment by AlexBeischl** [comment]
We will continue using the old Polyline-Editor, it should work fine enough :wink:

**Comment by bandle** [comment]
#192
