### ISSUE TITLE
Host the maptiles

### ISSUE THREAD

**Issue by bandle** [Rostlab/JS16_ProjectC_Group10#159]
Is there a way to host the map tiles on the got.show domain?

For example on: tiles.got.show
This would be the folders:
- bg  
- labels
  and the file blank.png

So we can access the tiles like:
tiles.got.show/labels/0/y0x0.png

**Comment by sacdallago** [comment]
yes. Best we meet. Hope the showers work this time

**Comment by bandle** [comment]
Or we have a digital meeting. So you needn't use the bike at all ;)

**Comment by sacdallago** [comment]
Actually I cloned the github repo, and the tiles are in the repo, right? So if you go to http://map.got.show you are on the root of your repo, and the tiles should be somewhere around there? sub folderish? Can you try this out?

**Comment by sacdallago** [comment]
Bingo! http://map.got.show/tiles/bg/0/y0x0.png

**Comment by bandle** [comment]
Yes this works actually. 
The main idea behind the subdomain with only the tiles on it would be, that we can be sure it doesn't change. And we maybe could do it on a server only configured to serve static files, to speed it up.

Also I wanted to ask you before I use the tiles from your server, to be sure I don't produce to much traffic. :)

**Comment by sacdallago** [comment]
Sure, I'll look into the subdomain thinghy later. Just tell me which folder needs to be the root of tiles.got.show.
And yes! The idea is that I'm gonna service the tiles directly from the server, that's why I asked you to refactor that :) smthn like 127.0.0.1/tiles blablabla (so I avoid even going over DNS resolution :D :D )

**Comment by bandle** [comment]
It would be good to have:
BG Tiles: tiles.got.show/bg/{z}/y{y}x{x}.png
Label Tiles: tiles.got.show/labels/{z}/y{y}x{x}.png
Blank: tiles.got.show/blank.png

Just to show - This is the level of configuration possible yet:

```
var defaultOptions = {
        'filter':false,
        'timeline':false,
        'characterBox':false,
        'cityDetails':function(a,b) {internalHelpers.loadWikiPage(a,b);},
        'characterDetails':function(a,b) {internalHelpers.loadWikiPage(a,b);},
        'defaultPersonImg':'img/persons/dummy.jpg',
        'deadPersonImg':'img/persons/skull.png',
        'cityDataSource':'https://got-api.bruck.me/api/cities',
        'realmDataSource':'https://got-api.bruck.me/api/realms',
        'pathDataSource':'https://got-api.bruck.me/api/paths',
        'episodeDataSource':'https://got-api.bruck.me/api/episodes/',
        'characterDataSource':'https://got-api.bruck.me/api/characters/',
        'bgTiles':'https://raw.githubusercontent.com/Rostlab/JS16_ProjectC_Group10/develop/tiles/bg/{z}/y{y}x{x}.png',
        'labelTiles':'https://raw.githubusercontent.com/Rostlab/JS16_ProjectC_Group10/develop/tiles/labels/{z}/y{y}x{x}.png',
        'errorTile':'https://raw.githubusercontent.com/Rostlab/JS16_ProjectC_Group10/develop/tiles/blank.png',
        'characterColors':['#F44336', '#2196F3', '#4CAF50', '#212121', '#7C4DFF', '#F8BBD0', '#FBC02D', '#795548', 
        '#00796B', '#536DFE', '#FFFFFF', '#FF5722']
    };
```

**Comment by sacdallago** [comment]
Amazeballs :+1: I like that you also included the `https` so that I can change it to insecure http :D who cares about encryption anyway

**Comment by sacdallago** [comment]
@ http://tiles.got.show  

Folder structure: 

``` bash
tiles$ ls
bg  blank.png  index.html  labels  overview
```

**Comment by bandle** [comment]
We already switched to the remote tiles #163
