### ISSUE TITLE
Prepare our code to work with the database

### ISSUE THREAD

**Issue by bandle** [Rostlab/JS16_ProjectC_Group10#164]
- [x] Cities
- [x] Characters
- [x] Episodes
- [x] Paths
- [x] City-Character
- [x] Realms/Regions
- [x] Character Images

**Comment by bandle** [comment]
Switched all sources back to our git due to massive DB problems

**Comment by sacdallago** [comment]
If the API's down, ask @Adiolis @kordianbruck @togiberlin etc for the config and how to run the API locally.
You anyway just need to change the endpoints from Bruck's server to localhost ;) This way you avoid the bottleneck

**Comment by bandle** [comment]
When I did this change I assumed that the server is just down for a hour or sth like that. 
And there was an issue already open.

**Comment by kordianbruck** [comment]
Sorry for the inconvenience. I can supply you with access to the mLab Database if you want to run the API locally. Let me know.

**Comment by bandle** [comment]
Switched everything back to DB - working again :+1: 
#187

**Comment by bandle** [comment]
Everything is prepared to work with DB - only https://github.com/Rostlab/JS16_ProjectA/issues/117 has to be done.

**Comment by kordianbruck** [comment]
Issue is done :)

**Comment by bandle** [comment]
#207 Done

Thank you @Adiolis and @kordianbruck
