### ISSUE TITLE
Add Character Paths

### ISSUE THREAD

**Issue by bandle** [Rostlab/JS16_ProjectC_Group10#171]
- [x] Petyr Baelish
- [x] Joffrey Baratheon
- [x] Myrcella Baratheon
- [x] Tommen Baratheon 
- [x] Robert Baratheon
- [x] Stannis Baratheon
- [x] Renly Baratheon
- [x] Khal Drogo
- [x] Tywin Lannister
- [x] Jaime Lannister
- [x] Cersei Lannister
- [x] Tyrion Lannister
- [x] Davos Seaworth
- [x] Eddard Stark
- [x] Catelyn Stark
- [x] Robb Stark
- [x] Sansa Stark
- [x] Arya Stark
- [x] Bran Stark
- [x] Rickon Stark
- [x] Jon Snow
- [x] Daenerys Targaryen
- [x] Viserys Targaryen
- [x] Samwell Tarly
- [x] Brienne of Tarth
- [x] Theon Greyjoy
- [x] Asha Greyjoy
- [x] Victarion Greyjoy

**Comment by AlexBeischl** [comment]
Added some more paths :smile: 
@gyachdav and @sacdallago : challenge accepted :wink: 

<img width="1011" alt="bildschirmfoto 2016-03-20 um 00 22 00" src="https://cloud.githubusercontent.com/assets/17533952/13901851/e26c07b6-ee31-11e5-859b-1077d0c82614.png">

**Comment by gyachdav** [comment]
Saweeeeettttt!!!

@AlexBeischl,this is a dream coming true!!  

Now let's try to find a way to free you from manually doing this and crowd source the shit out of this. Would be a great fan resource. I for one would love to know where I can find Pate and where Salahdor San went.

**Comment by AlexBeischl** [comment]
@gyachdav :
paths for 28 characters adden, challenge beaten :smile: #175

**Comment by bandle** [comment]
Live demo is now online: http://rostlab.github.io/JS16_ProjectC_Group10/

@sacdallago @gyachdav
