### ISSUE TITLE
Hint for the user on how to "ues" the Map

### ISSUE THREAD

**Issue by mammuth** [Rostlab/JS16_ProjectC_Group10#179]
we probably need a kind of (optional) HowTo for the user? 

Maybe a toast message or overlay telling ​_**“Add characters to the map! Use the timeline at the bottom to display their location history.”**_​

What do you think? 

cc @jorjo1

**Comment by AlexBeischl** [comment]
Hi @mammuth ,
I think the map is self-explaining, everyone should be able to use it :wink: 
If you really want this to be added, it would be a pretty bad idea, to have it done by us.
We have worked so much with the map, we won't get the user's problem :disappointed:

**Comment by yashha** [comment]
Yea it would be our job

**Comment by mammuth** [comment]
Alright, then we'll think about whether this is needed and come up with a suggestion :+1:

**Comment by sacdallago** [comment]
I like the idea, and @AlexBeischl is right! @mammuth you can ask your static content guy :)

**Comment by mammuth** [comment]
I don't think its totally self-explanatory for users that don't know the site and the map. 

Take this flow for example:
- DAU opens map-page. Sees a map with cities
- There is a search field that says "Search for..."
- DAU goes and enters what he thinks the map is about - cities: [typing slowly one letter after another, concentrated biting his tongue meanwhile] _"R...i...v...e...r...r...u...n"_
- Response is "Nothing found"
- DAU is all like :cry: 

Yo, static content guy @Andrew094, @sacdallago got some work for you :grin: 

PS: Did I mention, how damn awesome your map is?! :heart_eyes:

**Comment by gyachdav** [comment]
I agree, some hints are missing. Professor Rost also commented on that when I gave him a demo. 

For instance a tooltip would be nice over the flag icon, right now it is not clear what it does when pressed and a bunch of lines appear on the map.
