### ISSUE TITLE
more info link

### ISSUE THREAD

**Issue by yashha** [Rostlab/JS16_ProjectC_Group10#180]
Hey guys,
Your map is already embeded -> awsome result
https://got-stats.herokuapp.com/map

Can you tell us how to change the `More info` link?

**Comment by bandle** [comment]
You can Change The behavior by passing a callback function in the options. I think it's called personDetails. Just look it up in our wiki. 

If you want a different behavior than described there, just reopen the issue and describe what you want :)

**Comment by sacdallago** [comment]
Awesome @yashha 
Not to mention: I like the direction the page is going! Keep on working, great results

**Comment by gyachdav** [comment]
Hey guys any idea when this will be fixed?

**Comment by yashha** [comment]
@mbandle Do you know how to prevent the modal from showing?

**Comment by yashha** [comment]
I got it working :)

**Comment by sacdallago** [comment]
So closing this?
