### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by sacdallago** [Rostlab/JS16_ProjectC_Group10#181]
Hi guys,
I hope this is the last thing to toggle: I noticed the page is not rendered nicely on mobile phones.

It might be an option to hide the right menu and show it at some button click? At least on mobile
![screenshot_2016-03-21-09-51-18](https://cloud.githubusercontent.com/assets/6240943/13913865/cc20aa60-ef4a-11e5-9945-de0547452c94.png)

**Comment by bandle** [comment]
We added the possibility to fully change the maps appearance by stylesheets. So adding responsibility to our code would just be in the demo.js and demo.css . I don't know whether this helps team F or not as they only include the gotmap.js and css which comes with no predefined containers (for map, searcher, characters). 
They have all the possibilities to implement it themselves

**Comment by sacdallago** [comment]
I'm looking at your code, not the package. It's a nice to have, would put the cherry on top for your project :P :P :P
But if you think: _nah_, then close this annexing "will do in the future"

**Comment by bandle** [comment]
Then I'll do one responsive demo, just for you ;)

**Comment by sacdallago** [comment]
<3 I'm gonna have to bake cake for you then, at some stage. I mean, it will be the worst cake you'll ever try in your entire existence, but the though counts! :D :D

**Comment by bandle** [comment]
1st Test working :)

![bildschirmfoto 2016-03-21 um 14 20 02](https://cloud.githubusercontent.com/assets/11232638/13920318/b5a3e61c-ef72-11e5-8b31-09d05332ccc4.png)
![bildschirmfoto 2016-03-21 um 14 39 09](https://cloud.githubusercontent.com/assets/11232638/13920320/b5d184aa-ef72-11e5-96e1-a675e9dc2a0e.png)

Just minor bug fixing todo

**Comment by bandle** [comment]
@sacdallago 
It works: http://rostlab.github.io/JS16_ProjectC_Group10/

I'm looking forward to the cake :+1: :cake:

**Comment by sacdallago** [comment]
Gohohohood

**Comment by mammuth** [comment]
This isn't yet in 0.3.1, is it?

**Comment by bandle** [comment]
This is in none of the releases. Its just in the demo.js and demo.css
https://github.com/Rostlab/JS16_ProjectC_Group10/blob/develop/mockup/js/demo.js
https://github.com/Rostlab/JS16_ProjectC_Group10/blob/develop/mockup/css/demo.css

**Comment by mammuth** [comment]
Are you going to add this to the package itself?

**Comment by bandle** [comment]
I don't thinks so for two Reasons:
1. We had our feature freeze a week ago
2. We don't want to script the behavior of the HTML containers as this can result in big problems when integrating. 

The easiest way for you would be to just copy the demo scripts. The Responsive Magic Mainly takes part in the css

**Comment by mammuth** [comment]
Nah, just copying won't work because of the fixed-positioning in your demo :wink: But should be easy to adopt :+1:

**Comment by bandle** [comment]
:+1: And I think you can nearly copy the JS which makes the button

**Comment by sacdallago** [comment]
So many :+1: ;

:+1:
