### ISSUE TITLE
Daenerys Targaryyn dead at Vaes Dothrak

### ISSUE THREAD

**Issue by gyachdav** [Rostlab/JS16_ProjectC_Group10#183]
Seems like you guys killed Daenerys while she was at Vaes Dothrak during S1E5. Could it be that you mixed her up with http://awoiaf.westeros.org/index.php/Viserys_Targaryen?

**Comment by bandle** [comment]
For me she is alive 
![bildschirmfoto 2016-03-21 um 16 04 37](https://cloud.githubusercontent.com/assets/11232638/13922911/a78f300c-ef7e-11e5-9cfb-8292f8afa61b.png)

**Comment by bandle** [comment]
And Viserys correctly dies in Vaes Dothrak:  
![bildschirmfoto 2016-03-21 um 16 07 23](https://cloud.githubusercontent.com/assets/11232638/13922990/066daf9a-ef7f-11e5-8fee-4098a11ac1bf.png)

@gyachdav Can you provide more information on which domain the error occurred?

**Comment by gyachdav** [comment]
![screen shot 2016-03-21 at 11 10 17 am](https://cloud.githubusercontent.com/assets/4074881/13923109/9e76e65a-ef55-11e5-87e3-97ba5f9a9017.png)

She's looks pretty dead to me on this screen shot. When she decides to move to the next land mark she is resurrected :laughing:

**Comment by gyachdav** [comment]
btw, as part of opening this up to the public, ppl should be able to submit bugs and propose changes.

**Comment by bandle** [comment]
Interesting - for me the same screenshot looks like this: 
![bildschirmfoto 2016-03-21 um 16 14 31](https://cloud.githubusercontent.com/assets/11232638/13923242/0f578e5e-ef80-11e5-80c6-b047bef8f201.png)

**Comment by bandle** [comment]
Oh wait - I found it. The boolean alive was wrong in just one tilmestep :)

**Comment by bandle** [comment]
Fixed It - Should be online in 1-2 minutes

**Comment by gyachdav** [comment]
don't mean to be a dick, but Danny is no longer in Mereen at the end of S5E8

[Dothraki khalasar surrounds Daenerys](https://www.youtube.com/watch?v=jAk1japvt_0)

**Comment by AlexBeischl** [comment]
Hi Guy,
thank you, my mistake, after hours of creating paths I must have overseen it..., I will fix it.
We thought about a appeal to test the paths after finishing the features to find and correct such "bugs".
I fixed it.

**Comment by AlexBeischl** [comment]
Found some missing details, I'm correcting it right now

**Comment by gyachdav** [comment]
Thanks for the quick fix! 

As I mentioned before, I think that it'll be great that if (after delivery) we can come up with a mechanism that will allow us to crowd source the map. The opportunities are endless:
- create location for events: battles, tourney, duels, weddings, dragons spotting etc
- enter paths for minor characters. 
- Even create your own story. what if character A will go to X and meet character B.. okay thats a stretch but thought i mention it. 

I already see die hards sitting at their mom's basement for days making sure all characters are pinned to their proper location. 

Maybe worth opening a new issue to discuss the design of such an enhancement.
