### ISSUE TITLE
where's Robert Baratheon?

### ISSUE THREAD

**Issue by gyachdav** [Rostlab/JS16_ProjectC_Group10#185]
King Robert seems to be suspiciously missing from the map. Did the secret service asked you to make him disappear :stuck_out_tongue_winking_eye: 
![screen shot 2016-03-21 at 11 21 30 am](https://cloud.githubusercontent.com/assets/4074881/13923670/03b1572e-ef58-11e5-8e34-deeef20181d6.png)

**Comment by bandle** [comment]
I think we can pass this issue to the DB group as he isn't present there:

https://got-api.bruck.me/api/characters/Robert%20Baratheon

```
{"message":"Failure. No character with that data existing!","data":{"name":{"$regex":"Robert Baratheon","$options":"i"}}}
```

Same Problem for Brienne of Tarth

**Comment by bandle** [comment]
I close this issue as we can do nothing than wait for the DB to be refilled. Then the assigned path should be there
