### ISSUE TITLE
Test-Phase for paths

### ISSUE THREAD

**Issue by AlexBeischl** [Rostlab/JS16_ProjectC_Group10#191]
Start a test-phase to make sure all paths are correct

**Comment by gyachdav** [comment]
Bring Jon Snow back home to castle black!! :smile: at the end of S5 he is still stuck in Hardhome

**Comment by AlexBeischl** [comment]
Hi @gyachdav ,
I've added his path already and merged it, so Jon comes home to Castle Black... unfortunately :cry: 
I will talk to Christian, to update the data :smile: 
<img width="1273" alt="bildschirmfoto 2016-03-23 um 16 59 13" src="https://cloud.githubusercontent.com/assets/17533952/13991474/9d696f34-f118-11e5-90b2-761e7d26cea5.png">

**Comment by gyachdav** [comment]
Thanks. Also make sure that F pulls a new ver of your pack every once in a while. Their ver is very outdated.

**Comment by sacdallago** [comment]
@gyachdav packs this project usually

@AlexMoroz can you repack please? I know it's just changing the code version, buuuuuut :D :D

Merci :kissing:

**Comment by AlexBeischl** [comment]
We will combine the test-phase with the editor, makes more sense :smile:

**Comment by gyachdav** [comment]
Joffrey survived! running the timeline to S5e10 I don't get a skulled pin

**Comment by gyachdav** [comment]
Same goes for King Robert

**Comment by bandle** [comment]
It's not an error in our path data - its only a display issue because we have a start and an end pin for each route. And in the case of Robert and Joffrey these are the same. So you only see the start pin.

I'll change the order of the markers.
