### ISSUE TITLE
Doc not complete

### ISSUE THREAD

**Issue by yashha** [Rostlab/JS16_ProjectC_Group10#197]
1. If I search for a character the character has to be lower case. (Need to be described in the docs)
2. The result of a search is always a array of character objects.
   So you need to call `mymap.addCharacter(character[0])`

**Comment by bandle** [comment]
1. We'll add the toLower to the input. 
2. We'll add it to the docs. 

Thanks for testing :)

**Comment by yashha** [comment]
No problem ;)
I'm currently integrating it in the characters page :)
