### ISSUE TITLE
'cityDetails' when clicking on the city name

### ISSUE THREAD

**Issue by mammuth** [Rostlab/JS16_ProjectC_Group10#212]
Right now the cityDetails-Event is only triggered when clicking on the city-icon. It would make sense to also fire this event when clicking on the city-name.

**Comment by bandle** [comment]
I`ll have a look in the plugin we use to display the labels. If it's possible we'll change it tomorrow.

**Comment by sacdallago** [comment]
This is on the border between FF and deadline. This request shall pass :D

**Comment by bandle** [comment]
By default the label doen't support anything like this. I'll check how hard it is to mod the plugin.

**Comment by bandle** [comment]
It works

http://rostlab.github.io/JS16_ProjectC_Group10/
