### ISSUE TITLE
Toggle search bar

### ISSUE THREAD

**Issue by gyachdav** [Rostlab/JS16_ProjectC_Group10#213]
The individual character page loads the map component, but there it makes less sense to keep the search bar open (or at least have it turned off by default). 

Does the init func or API include an option to toggle the search bar?

@mammuth

**Comment by bandle** [comment]
Our API Offers Options to fully customize the layout. 
You can control the visibility of the searchbar by individual scripts, as you also pass in the input field which should be used. Also you can off course assign css classes and styles.

The [demo](http://map.got.show) shows this by featuring a responsive version. The character list is hidden by default on mobile devices or small browser windows. Also buttons are faded in dynamically like the character button in the top right of the map which toggles the character list
![bildschirmfoto 2016-03-26 um 23 54 53](https://cloud.githubusercontent.com/assets/11232638/14062837/2eb96344-f3ae-11e5-9305-c9c9586abd67.png)

**Comment by mammuth** [comment]
@gyachdav I already removed the search bar in a commit, but this one had to be reverted. Going to change this again tomorrow.
