### ISSUE TITLE
Images not loading

### ISSUE THREAD

**Issue by yashha** [Rostlab/JS16_ProjectC_Group10#214]
https://got-stats.herokuapp.com/map
![screenshot from 2016-03-27 00 01 32](https://cloud.githubusercontent.com/assets/4728786/14062879/4d28ddae-f3af-11e5-9215-a36423c9a63d.png)
![screenshot from 2016-03-27 00 01 51](https://cloud.githubusercontent.com/assets/4728786/14062880/50f420f6-f3af-11e5-9067-133a1a7ea05a.png)

**Comment by bandle** [comment]
![bildschirmfoto 2016-03-27 um 00 05 47](https://cloud.githubusercontent.com/assets/11232638/14062888/ba44dbfe-f3af-11e5-8a9a-aa0b869a32c8.png)

Our Live version works: http://rostlab.github.io/JS16_ProjectC_Group10/

Looking where the error has its root …

**Comment by yashha** [comment]
Your urls:
https://got-api.bruck.me/misc/images/characters/Daenerys_Targaryen.jpeg
Our urls:
https://got-api.bruck.me/images/thumb/c/c6/Eddard_by_AniaEm.jpg/300px-Eddard_by_AniaEm.jpg

We have also different versions, maybe thats one factor

**Comment by bandle** [comment]
The online page has the live version (same as in the bundle)

**Comment by bandle** [comment]
The path comes directly from the DB "imageLink":"/misc/images/characters/Borroq.jpeg"
and is combined with the imageBasePath

**Comment by yashha** [comment]
I saw the problem:
gotdailysentiment@0.0.6 invalid
gotmap@0.1.2 invalid
gotsentimental@0.1.0 invalid
I have to check that

sry

**Comment by bandle** [comment]
You are loading an old version of our map.
You can check it by looking at the XHRs the new one calls the DB, the old one our github.
![bildschirmfoto 2016-03-27 um 00 16 56](https://cloud.githubusercontent.com/assets/11232638/14062917/3a2b3a7e-f3b1-11e5-88a9-e1c07ffac65b.png)

The version you're using is the one I built so quick fix the DB issues.

**Comment by yashha** [comment]
Ah thanks man, great help! :)

**Comment by bandle** [comment]
No Problem. You're welcome :)

**Comment by mammuth** [comment]
The default config seems to load the images from the wiki, right?
For me this is not working:
<img width="534" alt="screen shot 2016-03-27 at 22 19 57" src="https://cloud.githubusercontent.com/assets/3121306/14067674/32c1302c-f46a-11e5-91af-07276260f501.png">
http://awoiaf.westeros.org//misc/images/characters/Eddard_Stark.jpeg
Furthermore the link is not valid (two slashes after the host), however it's not resolving, when correcting this either.

Looks like the images are broken again :pensive:

**Comment by bandle** [comment]
The config should not load it from the wiki. The most recent version loads it from Koordians Server.
http://map.got.show
![bildschirmfoto 2016-03-27 um 22 25 08](https://cloud.githubusercontent.com/assets/11232638/14067698/cb983d0e-f46a-11e5-918e-0aa800fa490c.png)

**Comment by mammuth** [comment]
Alright, thanks. 
I love how our config is messy like hell :smirk:

**Comment by bandle** [comment]
@mammuth 
Which config do you mean?
Our got map config is documented ;)

https://github.com/Rostlab/JS16_ProjectC_Group10/wiki/Init-New-GoT-Map-and-Options

**Comment by mammuth** [comment]
Didn't mean yours. Yours is nice :+1:
