### ISSUE TITLE
Distance traverled

### ISSUE THREAD

**Issue by gyachdav** [Rostlab/JS16_ProjectC_Group10#218]
Is it possible to calculate the distance traveled by using the paths?

Would be cool if we can create a ranking of which character traveled the most and who likes to stay at home. 

@goldbergtatyana @mammuth @sacdallago @jorjo1

**Comment by AlexBeischl** [comment]
Hi Guy,

our feature freeze as well as your final delivery deadline have been on 21.3. & 25.3., therefore we shouldn't implement any new features in the map.
Additionally, we would like to focus on the editor the next days and implementing the paths shouldn't be done that easy :disappointed:

**Comment by sacdallago** [comment]
Deadlines are deadlines!
