### ISSUE TITLE
Locations no paths

### ISSUE THREAD

**Issue by sacdallago** [Rostlab/JS16_ProjectC_Group10#219]
Hey guys,
I don't know on whose side this is @yashha , but right now on the staging page you can't viz the paths, but only the locations! Neither on the char page, nor on the /map
![screen shot 2016-03-31 at 5 12 54 pm](https://cloud.githubusercontent.com/assets/6240943/14180578/f8b57d6e-f763-11e5-9253-41afb21227b2.png)

Also please update the default api location to api.got.show as http://rostlab.github.io/JS16_ProjectC_Group10/ is not working ;)

**Comment by bandle** [comment]
I updated the location and there are still no paths:

https://api.got.show/api/characters/paths

Your DB doesn't contain any of them, neither the hasPath is set at one of them. In my opinion there is a problem with the DB @sacdallago

**Comment by AlexMoroz** [comment]
@kordianbruck

**Comment by bandle** [comment]
Koordians got-api contained the mentioned attributes a week ago

**Comment by sacdallago** [comment]
There may be a problem with the DB then.
I have no idea how this was implemented by **A**, I followed the instructions on how to scrape the data. Any suggestions @Adiolis , @kordianbruck , @togiberlin , @boriside ?

**Comment by sacdallago** [comment]
I can give you also the mlab access so you have a look at the data

**Comment by ghost** [comment]
Did you run `npm run refill --collection=characterPaths`?

**Comment by bandle** [comment]
@Adiolis mentioned some refill command in the issue where he implemented it: https://github.com/Rostlab/JS16_ProjectA/issues/117#issuecomment-201478296

Maybe this helps

**Comment by sacdallago** [comment]
I'll try that right after the recalculation of pageranks finishes

**Comment by sacdallago** [comment]
Was that.
https://api.got.show/api/characters/paths

Thanks guys.

**Comment by bandle** [comment]
@sacdallago Is it possible that this fix broke the image locations?

**Comment by sacdallago** [comment]
I also noticed something weird on the link you sent me per email.
@Adiolis is there a way to check this

**Comment by sacdallago** [comment]
Btw, I still don't see the paths..?

https://got-stats.herokuapp.com/characters/Jeyne%20Arryn

![screen shot 2016-04-02 at 3 43 17 pm](https://cloud.githubusercontent.com/assets/6240943/14226696/bd8c960a-f8e9-11e5-88cf-fba80ece7d97.png)

**Comment by sacdallago** [comment]
CC @yashha @mammuth @mina-zaki @jorjo1

**Comment by bandle** [comment]
Our own demo works: http://rostlab.github.io/JS16_ProjectC_Group10/

Maybe they are still using an old package

**Comment by sacdallago** [comment]
@mbandle it works? For me it doesn't?!

![screen shot 2016-04-02 at 3 47 37 pm](https://cloud.githubusercontent.com/assets/6240943/14226711/46ba712c-f8ea-11e5-96e1-90220f176a08.png)

**Comment by bandle** [comment]
![bildschirmfoto 2016-04-02 um 15 48 33](https://cloud.githubusercontent.com/assets/11232638/14226715/6a0c1f90-f8ea-11e5-9a06-f7ece8b4e6ea.png)

**Comment by bandle** [comment]
I think Jayne Arryn simply has no path assigned

**Comment by sacdallago** [comment]
Auuuuuuhhh, my bad :dancer:
