### ISSUE TITLE
tooltips?

### ISSUE THREAD

**Issue by gyachdav** [Rostlab/JS16_ProjectC_Group10#228]
Hey guys, i remember this was mentioned at some point that we would like to have tooltips for the flag button on the map and possibly for the zoom. Is that implemented? will it be implemented?

**Comment by bandle** [comment]
It is easily possible for the flag icon, but not for the zoom icons. But their function is in my opinion quite obvious. 

I'll just implement it in the evening. What describing text do you want to have when hovering it?

**Comment by gyachdav** [comment]
thanks! "show/hide regions" ?

**Comment by bandle** [comment]
Works http://rostlab.github.io/JS16_ProjectC_Group10/

![bildschirmfoto 2016-04-05 um 20 34 02](https://cloud.githubusercontent.com/assets/11232638/14293687/f18db7dc-fb6d-11e5-8896-8cecd0afa344.png)
