### ISSUE TITLE
more info link breaks to new line because of too long house names

### ISSUE THREAD

**Issue by yashha** [Rostlab/JS16_ProjectC_Group10#234]
![image](https://cloud.githubusercontent.com/assets/4728786/14302293/9bc4b936-fb9f-11e5-9ab3-4e29e9dd24c2.png)

**Comment by bandle** [comment]
```
.gotmap-character .character .house {
overflow: hidden;
text-overflow: ellipsis;
padding-right: 1em;
white-space: pre;
}
```

I'll add it to our css.
![bildschirmfoto 2016-04-06 um 09 17 55](https://cloud.githubusercontent.com/assets/11232638/14308760/781ec196-fbd8-11e5-970c-43ba56153d36.png)
