### ISSUE TITLE
database cleanup

### ISSUE THREAD

**Issue by gyachdav** [Rostlab/JS16_ProjectC_Group10#235]
Attached are some false positive char-location associations I found in the db. As you can see many characters somehow appear to be in Lys, Myr or Valeria e.g. many Starks in Lys. You can use the attached list to do some db cleanup. 

[chars-loc - Sheet2.csv.txt](https://github.com/Rostlab/JS16_ProjectC_Group10/files/205694/chars-loc.-.Sheet2.csv.txt)

**Comment by bandle** [comment]
@gyachdav we can't do anything about the data we get from the database, we just display them.

I think this is more an issue for Group A 
@Adiolis Do you see to process the csv when gathering the character location info?

**Comment by sacdallago** [comment]
@adiolis @kordianbruck what's the rationale behind scraping Locations? The Infobox?
If that is the case, then the way to fix this is by updating the wiki directly.
@togiberlin please take a look at the CSV of Guy and update accordingly, if the work is too much @kordianbruck and @boriside can help

**Comment by ghost** [comment]
@sacdallago Nope, the whole text is used to look for city mentionings.
There is no special pattern in the wiki pages.

**Comment by sacdallago** [comment]
Ha.
That's unfortunate :D can you explain the rationale further? Do you count the number of hits of a city and use a trashold, do you look for specific pre/post text, do you look for closeness of the char name to the location name or do you simply pick up every location name you find?

**Comment by gyachdav** [comment]
Nah ion told them to do it in the simplest way even if we get many false positives. The results are not bad but can be cleaned up.

**Comment by sacdallago** [comment]
I see, so let's open an issue on **A** then @gyachdav ?
