### ISSUE TITLE
Search bar covered by navi on mobile 

### ISSUE THREAD

**Issue by gyachdav** [Rostlab/JS16_ProjectC_Group10#251]
Makes searching the map impossible on mobile. Tested in iPhone 6

**Comment by AlexBeischl** [comment]
Hi @gyachdav ,

this is already an issue for Group F: https://github.com/Rostlab/JS16_ProjectF/issues/427
Furthermore, we have implemented another searchbar, this one was chosen and implemented by Group F. 😉
