### ISSUE TITLE
Two questions concerning the DB and UI:

### ISSUE THREAD

**Issue by AlexBeischl** [Rostlab/JS16_ProjectC_Group10#29]
We had a Skype conference with Alex today and two questions appeared/remain:

Should we use geographic data from the DB of Team A? 
By now, the DB doesn’t support any location data or coordinates. Therefore, we have found additional datasources to generate them yourself via our editor. Can we use those self generated data instead or should we import those data into the database of Project A?

How much of the User Interface do you expect us to do? 
As far as we understood, we provide the whole map with a UI yourself and Project F integrates it into the project. 
So for example, if they use a menubar to navigate, we provide the space for the bar in our UI and they insert their navigation structure.
Did we get this correctly?

**Comment by gyachdav** [comment]
Yes please integrate as much data as you can from project A. If project A did not populate the data or missing some data items that you have access to, then coordinate with A the ways that you can import your data into the db. They will be able to provide you with a token that will let you POST to their API. 

Your understanding of the integration with project F is correct. Make sure you reach out to them to confirm your assumptions and coordinate the integration. The sooner you do this the better.

**Comment by sacdallago** [comment]
I read now. Thanks @gyachdav and yes: he said everything there is to say. I only add: very good that you have come up with a solution to create your own data, very much appreciated, very nice to see!
