### ISSUE TITLE
Please don't close your own pull requests

### ISSUE THREAD

**Issue by sacdallago** [Rostlab/JS16_ProjectC_Group10#4]
@mbandle when you open a pull request, make sure another member of your team approves and merges your requests. This ensures that there is consensus on your code and that someone else read your work.

**Comment by bandle** [comment]
I only did it because the things I pushed were already in the repository before.

**Comment by sacdallago** [comment]
Apple is not ready to crack iPhone encryption although asked for a very good reason to not create precedent @mbandle :smile: You just created a precedent!
Don't do it anymore, please.

**Comment by bandle** [comment]
Ok :+1:
