### ISSUE TITLE
Show city details

### ISSUE THREAD

**Issue by bandle** [Rostlab/JS16_ProjectC_Group10#51]
- [x] Open modul on click on city
- [x] Dynamically load the wiki contents in
- [x] Filter out menus, ads, …
- [x] Beautify it

**Comment by bandle** [comment]
It Works 
![bildschirmfoto 2016-03-06 um 18 42 10](https://cloud.githubusercontent.com/assets/11232638/13555836/2dbabb02-e3cb-11e5-88a2-586e2ff63560.png)

**Comment by sacdallago** [comment]
I **like** this.

**Comment by goldbergtatyana** [comment]
So super cool!

**Comment by bandle** [comment]
And in the Footer Line there are the categories and a link to the original wiki page:
![bildschirmfoto 2016-03-06 um 22 21 40](https://cloud.githubusercontent.com/assets/11232638/13557160/5c4738a0-e3ea-11e5-84f8-2b5eaab384cb.png)

**Comment by goldbergtatyana** [comment]
Stunning! Looks amazing! Thx Max :)
