### ISSUE TITLE
Nice PHP + bash, but... this is JS Seminar!

### ISSUE THREAD

**Issue by sacdallago** [Rostlab/JS16_ProjectC_Group10#7]
https://github.com/Rostlab/JS16_ProjectC_Group10/tree/develop/tiles

:dancer: just saying

**Comment by bandle** [comment]
Should I rewrite them? We just needed them once to fix the problems with the HBO Tiles, because they had some serious scaling issues. Now our js works better then theirs :)

**Comment by sacdallago** [comment]
Well, it would be really nice if you could at least rewrite the PHP to JS, you know :wink:

**Comment by sacdallago** [comment]
I mean: although you won't need it anymore, although you are quicker with PHP,...
Get out from your comfort zone! This seminar is about that! Make use of us!

**Comment by bandle** [comment]
Ok I´ll rewrite it with the html5 canvas lib in the evening

**Comment by bandle** [comment]
Done. I used nodjs with lwip - hope thats ok

**Comment by sacdallago** [comment]
That's great!
