### ISSUE TITLE
Add a Wall to the map label layer

### ISSUE THREAD

**Issue by bandle** [Rostlab/JS16_ProjectC_Group10#88]
Add the moment our bg doesn't feature a wall
- [x] Design a wall
- [x] Add it to the labels layer
- [x] Export it and bring it to the mockup

**Comment by bandle** [comment]
![bildschirmfoto 2016-03-09 um 00 22 19](https://cloud.githubusercontent.com/assets/11232638/13620038/05030872-e58d-11e5-8612-92a433fcebc3.png)

Works

**Comment by gyachdav** [comment]
Nice!
