### ISSUE TITLE
Labels of the Wall

### ISSUE THREAD

**Issue by AlexBeischl** [Rostlab/JS16_ProjectC_Group10#94]
Adapt Labels of the castles of the wall when zooming from Zoom4 -> Zoom5:

Zoom4:
<img width="393" alt="bildschirmfoto 2016-03-08 um 17 07 39" src="https://cloud.githubusercontent.com/assets/17533952/13607580/2416b9d4-e551-11e5-83d9-989df97bdcad.png">

Zoom5:
<img width="663" alt="bildschirmfoto 2016-03-08 um 17 07 34" src="https://cloud.githubusercontent.com/assets/17533952/13607406/4b403ca2-e550-11e5-9952-ce0bb42b9ac6.png">

The labels need to be rotated as well

**Comment by sacdallago** [comment]
OMG who the hell is assigned?!?!!! ahaha

**Comment by bandle** [comment]
Too many Maxes :D

**Comment by bandle** [comment]
Done

![bildschirmfoto 2016-03-16 um 15 17 35](https://cloud.githubusercontent.com/assets/11232638/13815346/82cb61ca-eb8a-11e5-97db-3af392343e41.png)
